### ISSUE TITLE
Can't find Desktop

### ISSUE THREAD

**Issue by dannyward630** [darkmatter2222/EVE-Online-Bot#7]
Hi there. When I run Miner.py, it throws this:
Traceback (most recent call last):
  File "D:\This PC\EVE-Online-Bot-main\MiningBot\Miner.py", line 5, in <module>
    from MiningBot.EveInterface.Interface import Interface
  File "D:\This PC\EVE-Online-Bot-main\MiningBot\EveInterface\Interface.py", line 16, in <module>
    UC = Universal_Prediction()
  File "D:\This PC\EVE-Online-Bot-main\ML_Components\Universal_Prediction.py", line 33, in __init__
    self.config = json.load(open(self.config_dir))[socket.gethostname()]
KeyError: 'DESKTOP-V538SGJ'

I can't seem to find what exactly is wrong.

**Comment by darkmatter2222** [comment]
Hold for a bit, improving the solution and extracting it out to here https://github.com/darkmatter2222/ml_botting_core, making this more useable for people.

**Comment by darkmatter2222** [comment]
Status update: I have the new core stable. I will migrate the Miner Logic into the new core.   This new logic is rather friendly out of the box.

**Comment by dannyward630** [comment]
That's great. Thanks so much.

**Comment by darkmatter2222** [comment]
@dannyward630, making progress, also made a configuration layer: https://www.youtube.com/watch?v=fqIvihY5VO0

**Comment by darkmatter2222** [comment]
@dannyward630 
check out the read me

you might need to remap the hotkeys

**Comment by darkmatter2222** [comment]
Let me know if there are any other things I can support!
