### ISSUE TITLE
Eve database query

### ISSUE THREAD

**Issue by coreySean** [darkmatter2222/EVE-Online-Bot#9]
Is there some config or something I need for eve database to setup? Or can i disable mondodb logging somewhere? I couldn't find the setting or documentation for this.

Reading the history py file:
self.client = MongoClient(ag.mongo_logging['mining_bot']['mongo_host'],
                                  username=os.getenv("eve_username"),
                                  password=os.getenv("eve_password"))
        self.db = self.client[ag.mongo_logging['mining_bot']['db_name']]
        self.collection = self.db[ag.mongo_logging['mining_bot']

Which seems to be configured from ai_pilot_config_v2.json (but I cannot se wher eve_username / eve_password is from?

So far i've followed the tutorial and have configured everything but when tryingt o run the headless miner i get the below crash.

,
  "mongo_logging": {
   "mining_bot": {
    "mongo_host": "mongodb+srv://cluster0.ufnlr1u.mongodb.net/?retryWrites=true&w=majority",
    "mongo_authMechanism": "SCRAM-SHA-256",
    "db_name": "Eve",
    "collection_name": "History"
   },
  "mongo_logging": {
   "mining_bot": {
    "mongo_host": "mongodb+srv://cluster0.ufnlr1u.mongodb.net/?retryWrites=true&w=majority",
    "mongo_authMechanism": "SCRAM-SHA-256",
    "db_name": "Eve",
    "collection_name": "History"
   }

Is there a db structure I can copy from somewhere to instantiate the local db or should this be accessing to an online db? 

['collection_name']]
        self.temp = 0

`Traceback (most recent call last):
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 89, in _resolve_uri
    results = _resolve(
              ^^^^^^^^^
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\srv_resolver.py", line 43, in _resolve
    return resolver.resolve(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 1368, in resolve
    return get_default_resolver().resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 1201, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py", line 704, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query _mongodb._tcp.cluster0.ufnlr1u.mongodb.net. IN SRV:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Corey\Desktop\EVE-Online-Bot-main\Start_AI_Pilot.py", line 53, in <module>
    start_mining(params.config_file)
  File "C:\Users\Corey\Desktop\EVE-Online-Bot-main\AI_Pilot\Objectives\Mining\StartMining.py", line 28, in start_mining
    Bot.ag.log = History(Bot.ag)
                 ^^^^^^^^^^^^^^^
  File "C:\Users\Corey\Desktop\EVE-Online-Bot-main\AI_Pilot\Audit_History\History.py", line 29, in __init__
    self.client = MongoClient(ag.mongo_logging['mining_bot']['mongo_host'],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Corey\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymongo\mongo_client.py", line 736, in __init__`

**Comment by darkmatter2222** [comment]
Great idea! 

On mobile ATM, however this class can have a global config value added to bypass and disable. 

https://github.com/darkmatter2222/EVE-Online-Bot/blob/main/AI_Pilot/Audit_History/History.py

Time is limited right now, feel free to submit a PR and I can test/approve. Otherwise, this is a great engagement I can add in some time.

**Comment by darkmatter2222** [comment]
@coreySean,
here is an example of how to disable audit trail, ([https://github.com/darkmatter2222/EVE-Online-Bot/pull/10](https://github.com/darkmatter2222/EVE-Online-Bot/pull/10)) 

Feel free to try those change out.  When I have more time, I will test and merge in.  

Note, the audit feature we are discussing is not critical to the functionality of the bot. it only uploads activity to a MongoDB do the performance of the pot can be measured and monitored remotely. the PR I have linked above disabled that feature entirely.

However, if you want to get it working you will need to be proficient in mongo and python and stand up a cloud mongo cluster and enter your mongo creds in a .env  file in your user profile.  Considering the nature of your question, it might be easier to disable the mongo audit trail.

**Comment by darkmatter2222** [comment]
merged as part of this https://github.com/darkmatter2222/EVE-Online-Bot/pull/11
